# ------------------------------------
# -------- Project Information -------
# ------------------------------------
site_name: NCAR MkDocs Template
site_description: A template for creating NCAR mkdocs
repo_url: https://github.com/NCAR/NCAR_mkdocs_template/
site_url: https://NCAR.github.io/NCAR_mkdocs_template/
site_author: CISL CSG (Consulting Services Group)
edit_uri: edit/main/docs/

# directories to watch for automatic rebuilding when running "mkdocs serve"
watch:
  - mkdocs.yml
  - themes/
  - docs/

# ------------------------------------
# -------- validation config ---------
# ------------------------------------
validation:
  nav:
    not_found: warn             # check if stubs exist or not!
    omitted_files: ignore       # check for files that exist without any links to them in nav
    absolute_links : warn       # check for absolute links -- pointers to outside htmls in nav

  links:
    not_found: ignore           # check for broken links inside mds. (to be activated later!)
    absolute_links : ignore     # check for absolute links -- pointers to outside htmls in files (to be activated later!)
    unrecognized_links: ignore  # unrecognized relative links (to be activated later!)

# ------------------------------------
# ----------- content ----------------
# ------------------------------------
nav:
  - Home : index.md

  - How to Use This Template?: getting-started.md

# ------------------------------------
# -- configuration - themes
# (note theme.yml should be a symbolic link to one of several options'
# ------------------------------------
INHERIT: theme.yml

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML

copyright: '&copy; 2024 UCAR, Licensed under the <a href="https://creativecommons.org/licenses/by-sa/4.0/">Creative Commons CC-BY-SA 4.0</a>.'

# ------------------------------------
# -- configuration - extensions
# ------------------------------------
markdown_extensions:
  - meta
  - attr_list
  - footnotes
  - admonition
  - md_in_html
  - def_list
  - toc:
      permalink: true
      title: "Page Outline"

  # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
     url_download: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - codehilite:
      guess_lang: true

  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols:
      fractions: false
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# ------------------------------------
# -- configuration - extensions
# ------------------------------------
plugins:
  - search:
      enabled: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
  - minify:
      minify_html: true
  - open-in-new-tab
  - redirects:
      redirect_maps:
        'nhug/index.md': 'https://nhug.readthedocs.io/en/latest/'

# ------------------------------------
# -- configuration - extras
# ------------------------------------
extra:
  analytics:
    provider: google
    property: G-RZLJ37D0K6
  social:
    - icon: material/home-circle
      link: https://arc.ucar.edu/
    - icon: material/help-circle
      link: https://ithelp.ucar.edu/plugins/servlet/desk/site/rc
    - icon: fontawesome/brands/github
      link: https://github.com/NCAR
