# ------------------------------------
# -------- Project Information -------
# ------------------------------------
site_name: UCAR Software Engineering Assembly
site_description: The public facing site for the UCAR SEA featuring news, event information, and best practices.
repo_url: https://github.com/UCAR-SEA/sea-website
repo_name: UCAR-SEA/sea-website
site_url: https://UCAR-SEA.github.io/sea-website
site_author: SEA Steering Committee
edit_uri: edit/main/docs/

# directories to watch for automatic rebuilding when running "mkdocs serve"
watch:
  - mkdocs.yml
  - themes/
  - docs/

# ------------------------------------
# -------- validation config ---------
# ------------------------------------
validation:
  nav:
    not_found: warn             # check if stubs exist or not!
    omitted_files: ignore       # check for files that exist without any links to them in nav
    absolute_links : warn       # check for absolute links -- pointers to outside htmls in nav

  links:
    not_found: ignore           # check for broken links inside mds. (to be activated later!)
    absolute_links : ignore     # check for absolute links -- pointers to outside htmls in files (to be activated later!)
    unrecognized_links: ignore  # unrecognized relative links (to be activated later!)

# ------------------------------------
# ----------- content ----------------
# ------------------------------------
nav:
  #  - Home: index.md
  - Home:
    - index.md
  - ISS Conference:
    - iss/index.md
    - 2025: 
      - Conference: iss/2025.md
      - Program: iss/2025-program.md
      - Proceedings: iss/2025-proceedings.md
    - 2024: 
      - Conference: iss/2024.md
  - Open Discussions: discussions/index.md
  - Community:
    - community/index.md
    - Slack: https://ucarsea.slack.com
    - Mailing List: community/listserv.md
  - About Us:
    - about/index.md
    - Legacy Site Archive: archive/index.md

# ------------------------------------
# -- configuration - themes
# (note theme.yml should be a symbolic link to one of several options'
# ------------------------------------
INHERIT: theme.yml

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML

copyright: '
  <div class="ucar_links">
    <span>&copy; 2024 UCAR</span>
    <span><a href="https://www.ucar.edu/accessibility">Accessibility</a></span>
    <span><a href="https://www.ucar.edu/cookie-other-tracking-technologies-notice">Cookies</a></span>
    <span><a href="https://www.ucar.edu/notification-copyright-infringement-digital-millenium-copyright-act">Copyright Issues</a></span>
    <span><a href="https://www.ucar.edu/who-we-are/ethics-integrity/nondiscrimination">Nondiscrimination</a></span>
    <span><a href="https://www.ucar.edu/privacy-notice">Privacy</a></span>
    <span><a href="https://www.ucar.edu/terms-of-use">Terms of Use</a></span>
    <span><a href="https://ncar.ucar.edu/">NSF NCAR Home</a></span>
    <span><a href="https://www.ucar.edu/">UCAR Home</a></span>
  </div>
  <p class="bold">Postal Address:</p> P.O. Box 3000, Boulder, CO 80307-3000 • <p class="bold">Shipping Address:</p> 3090 Center Green Drive, Boulder, CO 80301'

# ------------------------------------
# -- configuration - extensions
# ------------------------------------
markdown_extensions:
  - meta
  - attr_list
  - footnotes
  - admonition
  - md_in_html
  - def_list
  - toc:
      permalink: "🔗&#xFE0E;"

  # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
     url_download: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - codehilite:
      guess_lang: true

  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols:
      fractions: false
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# ------------------------------------
# -- configuration - extensions
# ------------------------------------
plugins:
  - search:
      enabled: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
      manual: true
  - minify:
      minify_html: true
  - open-in-new-tab
#  - redirects:
#      redirect_maps:
#        'index.md': 'blog/index.md'
  - blog:
      blog_dir: .

  - redirects:
      redirect_maps:
        'conference/index.md': 'iss/index.md'
        'conference/2024.md': 'iss/2024.md'

# ------------------------------------
# -- configuration - extras
# ------------------------------------
extra:
  social:
    - icon: material/home-circle
      link: https://sea.ucar.edu
    - icon: material/slack
      link: https://ucarsea.slack.com
    - icon: material/email
      link: mailto:sea_committee@ucar.edu
