authors:
  vanderwb:
    name: Brian Vanderwende
    description: SEA Steering Committee
    avatar: assets/authors/vanderwb.jpg
  haiyingx:
    name: Haiying Xu
    description: SEA Steering Committee
    avatar: assets/authors/haiyingx.jpg
