name: Verify Default Styles

on: [pull_request]

jobs:
  check_default_themes:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Verify theme.yml
        run: |
          [[ -L theme.yml ]]                                || { echo "ERROR: theme.yml should be a symlink -> themes/SEA.yml"; exit 1; }
          [[ "$(readlink theme.yml)" == "themes/SEA.yml" ]] || { echo "ERROR: theme.yml should be a symlink -> themes/SEA.yml"; exit 1; }
